name: recommendation-system
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - jupyter
  - notebook
  - pandas
  - scikit-learn
  - scikit-surprise
  - pytorch
  - matplotlib
  - seaborn